name: verify plugin

on: workflow_call

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - uses: actions/cache@v4
      with:
        path: ~/.gradle/wrapper
        key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - name: verify plugin
      run: ./gradlew verifyPlugin --no-daemon --max-workers 2